export const countries = [
  { value: "af", label: "أفغانستان - Afghanistan" },
  { value: "al", label: "ألبانيا - Albania" },
  { value: "dz", label: "الجزائر - Algeria" },
  { value: "as", label: "ساموا الأمريكية - American Samoa" },
  { value: "ad", label: "أندورا - Andorra" },
  { value: "ao", label: "أنغولا - Angola" },
  { value: "ai", label: "أنغويلا - Anguilla" },
  { value: "ag", label: "أنتيغوا وبربودا - Antigua and Barbuda" },
  { value: "ar", label: "الأرجنتين - Argentina" },
  { value: "am", label: "أرمينيا - Armenia" },
  { value: "aw", label: "أروبا - Aruba" },
  { value: "au", label: "أستراليا - Australia" },
  { value: "at", label: "النمسا - Austria" },
  { value: "az", label: "أذربيجان - Azerbaijan" },
  { value: "bs", label: "الباهاما - Bahamas" },
  { value: "bh", label: "البحرين - Bahrain" },
  { value: "bd", label: "بنغلاديش - Bangladesh" },
  { value: "bb", label: "باربادوس - Barbados" },
  { value: "by", label: "بيلاروسيا - Belarus" },
  { value: "be", label: "بلجيكا - Belgium" },
  { value: "bz", label: "بليز - Belize" },
  { value: "bj", label: "بنين - Benin" },
  { value: "bm", label: "برمودا - Bermuda" },
  { value: "bt", label: "بوتان - Bhutan" },
  { value: "bo", label: "بوليفيا - Bolivia" },
  { value: "ba", label: "البوسنة والهرسك - Bosnia and Herzegovina" },
  { value: "bw", label: "بوتسوانا - Botswana" },
  { value: "br", label: "البرازيل - Brazil" },
  { value: "io", label: "إقليم المحيط الهندي البريطاني - British Indian Ocean Territory" },
  { value: "bn", label: "بروناي - Brunei" },
  { value: "bg", label: "بلغاريا - Bulgaria" },
  { value: "bf", label: "بوركينا فاسو - Burkina Faso" },
  { value: "bi", label: "بوروندي - Burundi" },
  { value: "kh", label: "كمبوديا - Cambodia" },
  { value: "cm", label: "الكاميرون - Cameroon" },
  { value: "ca", label: "كندا - Canada" },
  { value: "cv", label: "الرأس الأخضر - Cape Verde" },
  { value: "ky", label: "جزر كايمان - Cayman Islands" },
  { value: "cf", label: "جمهورية أفريقيا الوسطى - Central African Republic" },
  { value: "td", label: "تشاد - Chad" },
  { value: "cl", label: "تشيلي - Chile" },
  { value: "cn", label: "الصين - China" },
  { value: "cx", label: "جزيرة الكريسماس - Christmas Island" },
  { value: "cc", label: "جزر كوكوس - Cocos Islands" },
  { value: "co", label: "كولومبيا - Colombia" },
  { value: "km", label: "جزر القمر - Comoros" },
  { value: "cg", label: "الكونغو - Congo" },
  { value: "cd", label: "جمهورية الكونغو الديمقراطية - Congo (DRC)" },
  { value: "ck", label: "جزر كوك - Cook Islands" },
  { value: "cr", label: "كوستاريكا - Costa Rica" },
  { value: "ci", label: "ساحل العاج - Ivory Coast" },
  { value: "hr", label: "كرواتيا - Croatia" },
  { value: "cu", label: "كوبا - Cuba" },
  { value: "cy", label: "قبرص - Cyprus" },
  { value: "cz", label: "التشيك - Czechia" },
  { value: "dk", label: "الدنمارك - Denmark" },
  { value: "dj", label: "جيبوتي - Djibouti" },
  { value: "dm", label: "دومينيكا - Dominica" },
  { value: "do", label: "جمهورية الدومينيكان - Dominican Republic" },
  { value: "ec", label: "الإكوادور - Ecuador" },
  { value: "eg", label: "مصر - Egypt" },
  { value: "sv", label: "السلفادور - El Salvador" },
  { value: "gq", label: "غينيا الاستوائية - Equatorial Guinea" },
  { value: "er", label: "إريتريا - Eritrea" },
  { value: "ee", label: "إستونيا - Estonia" },
  { value: "sz", label: "إسواتيني - Eswatini" },
  { value: "et", label: "إثيوبيا - Ethiopia" },
  { value: "fk", label: "جزر فوكلاند - Falkland Islands" },
  { value: "fo", label: "جزر فارو - Faroe Islands" },
  { value: "fj", label: "فيجي - Fiji" },
  { value: "fi", label: "فنلندا - Finland" },
  { value: "fr", label: "فرنسا - France" },
  { value: "gf", label: "غويانا الفرنسية - French Guiana" },
  { value: "pf", label: "بولينيزيا الفرنسية - French Polynesia" },
  { value: "tf", label: "الأقاليم الجنوبية الفرنسية - French Southern Territories" },
  { value: "ga", label: "الغابون - Gabon" },
  { value: "gm", label: "غامبيا - Gambia" },
  { value: "ge", label: "جورجيا - Georgia" },
  { value: "de", label: "ألمانيا - Germany" },
  { value: "gh", label: "غانا - Ghana" },
  { value: "gi", label: "جبل طارق - Gibraltar" },
  { value: "gr", label: "اليونان - Greece" },
  { value: "gl", label: "جرينلاند - Greenland" },
  { value: "gd", label: "غرينادا - Grenada" },
  { value: "gp", label: "جوادلوب - Guadeloupe" },
  { value: "gu", label: "غوام - Guam" },
  { value: "gt", label: "غواتيمالا - Guatemala" },
  { value: "gg", label: "غيرنزي - Guernsey" },
  { value: "gn", label: "غينيا - Guinea" },
  { value: "gw", label: "غينيا بيساو - Guinea-Bissau" },
  { value: "gy", label: "غيانا - Guyana" },
  { value: "ht", label: "هايتي - Haiti" },
  { value: "hn", label: "هندوراس - Honduras" },
  { value: "hk", label: "هونغ كونغ - Hong Kong" },
  { value: "hu", label: "المجر - Hungary" },
  { value: "is", label: "آيسلندا - Iceland" },
  { value: "in", label: "الهند - India" },
  { value: "id", label: "إندونيسيا - Indonesia" },
  { value: "ir", label: "إيران - Iran" },
  { value: "iq", label: "العراق - Iraq" },
  { value: "ie", label: "أيرلندا - Ireland" },
  { value: "im", label: "جزيرة مان - Isle of Man" },
  { value: "il", label: "إسرائيل - Israel" },
  { value: "it", label: "إيطاليا - Italy" },
  { value: "jm", label: "جامايكا - Jamaica" },
  { value: "jp", label: "اليابان - Japan" },
  { value: "je", label: "جيرسي - Jersey" },
  { value: "jo", label: "الأردن - Jordan" },
  { value: "kz", label: "كازاخستان - Kazakhstan" },
  { value: "ke", label: "كينيا - Kenya" },
  { value: "ki", label: "كيريباس - Kiribati" },
  { value: "xk", label: "كوسوفو - Kosovo" },
  { value: "kw", label: "الكويت - Kuwait" },
  { value: "kg", label: "قرغيزستان - Kyrgyzstan" },
  { value: "la", label: "لاوس - Laos" },
  { value: "lv", label: "لاتفيا - Latvia" },
  { value: "lb", label: "لبنان - Lebanon" },
  { value: "ls", label: "ليسوتو - Lesotho" },
  { value: "lr", label: "ليبيريا - Liberia" },
  { value: "ly", label: "ليبيا - Libya" },
  { value: "li", label: "ليختنشتاين - Liechtenstein" },
  { value: "lt", label: "ليتوانيا - Lithuania" },
  { value: "lu", label: "لوكسمبورغ - Luxembourg" },
  { value: "mo", label: "ماكاو - Macao" },
  { value: "mg", label: "مدغشقر - Madagascar" },
  { value: "mw", label: "مالاوي - Malawi" },
  { value: "my", label: "ماليزيا - Malaysia" },
  { value: "mv", label: "المالديف - Maldives" },
  { value: "ml", label: "مالي - Mali" },
  { value: "mt", label: "مالطا - Malta" },
  { value: "mh", label: "جزر مارشال - Marshall Islands" },
  { value: "mq", label: "مارتينيك - Martinique" },
  { value: "mr", label: "موريتانيا - Mauritania" },
  { value: "mu", label: "موريشيوس - Mauritius" },
  { value: "yt", label: "مايوت - Mayotte" },
  { value: "mx", label: "المكسيك - Mexico" },
  { value: "fm", label: "ميكرونيسيا - Micronesia" },
  { value: "md", label: "مولدوفا - Moldova" },
  { value: "mc", label: "موناكو - Monaco" },
  { value: "mn", label: "منغوليا - Mongolia" },
  { value: "me", label: "الجبل الأسود - Montenegro" },
  { value: "ms", label: "مونتسرات - Montserrat" },
  { value: "ma", label: "المغرب - Morocco" },
  { value: "mz", label: "موزمبيق - Mozambique" },
  { value: "mm", label: "ميانمار - Myanmar" },
  { value: "na", label: "ناميبيا - Namibia" },
  { value: "nr", label: "ناورو - Nauru" },
  { value: "np", label: "نيبال - Nepal" },
  { value: "nl", label: "هولندا - Netherlands" },
  { value: "nc", label: "كاليدونيا الجديدة - New Caledonia" },
  { value: "nz", label: "نيوزيلندا - New Zealand" },
  { value: "ni", label: "نيكاراغوا - Nicaragua" },
  { value: "ne", label: "النيجر - Niger" },
  { value: "ng", label: "نيجيريا - Nigeria" },
  { value: "nu", label: "نيوي - Niue" },
  { value: "nf", label: "جزيرة نورفولك - Norfolk Island" },
  { value: "kp", label: "كوريا الشمالية - North Korea" },
  { value: "mp", label: "جزر ماريانا الشمالية - Northern Mariana Islands" },
  { value: "no", label: "النرويج - Norway" },
  { value: "om", label: "عمان - Oman" },
  { value: "pk", label: "باكستان - Pakistan" },
  { value: "pw", label: "بالاو - Palau" },
  { value: "ps", label: "فلسطين - Palestine" },
  { value: "pa", label: "بنما - Panama" },
  { value: "pg", label: "بابوا غينيا الجديدة - Papua New Guinea" },
  { value: "py", label: "باراغواي - Paraguay" },
  { value: "pe", label: "بيرو - Peru" },
  { value: "ph", label: "الفلبين - Philippines" },
  { value: "pn", label: "جزر بيتكيرن - Pitcairn Islands" },
  { value: "pl", label: "بولندا - Poland" },
  { value: "pt", label: "البرتغال - Portugal" },
  { value: "pr", label: "بورتو ريكو - Puerto Rico" },
  { value: "qa", label: "قطر - Qatar" },
  { value: "re", label: "ريونيون - Réunion" },
  { value: "ro", label: "رومانيا - Romania" },
  { value: "ru", label: "روسيا - Russia" },
  { value: "rw", label: "رواندا - Rwanda" },
  { value: "bl", label: "سانت بارتيليمي - Saint Barthélemy" },
  { value: "sh", label: "سانت هيلينا - Saint Helena" },
  { value: "kn", label: "سانت كيتس ونيفيس - Saint Kitts and Nevis" },
  { value: "lc", label: "سانت لوسيا - Saint Lucia" },
  { value: "mf", label: "سانت مارتن - Saint Martin" },
  { value: "pm", label: "سان بيير وميكلون - Saint Pierre and Miquelon" },
  { value: "vc", label: "سانت فينسنت والغرينادين - Saint Vincent and the Grenadines" },
  { value: "ws", label: "ساموا - Samoa" },
  { value: "sm", label: "سان مارينو - San Marino" },
  { value: "st", label: "ساو تومي وبرينسيب - Sao Tome and Principe" },
  { value: "sa", label: "السعودية - Saudi Arabia" },
  { value: "sn", label: "السنغال - Senegal" },
  { value: "rs", label: "صربيا - Serbia" },
  { value: "sc", label: "سيشيل - Seychelles" },
  { value: "sl", label: "سيراليون - Sierra Leone" },
  { value: "sg", label: "سنغافورة - Singapore" },
  { value: "sx", label: "سينت مارتن - Sint Maarten" },
  { value: "sk", label: "سلوفاكيا - Slovakia" },
  { value: "si", label: "سلوفينيا - Slovenia" },
  { value: "sb", label: "جزر سليمان - Solomon Islands" },
  { value: "so", label: "الصومال - Somalia" },
  { value: "za", label: "جنوب أفريقيا - South Africa" },
  { value: "gs", label: "جورجيا الجنوبية وجزر ساندويتش الجنوبية - South Georgia & South Sandwich Islands" },
  { value: "kr", label: "كوريا الجنوبية - South Korea" },
  { value: "ss", label: "جنوب السودان - South Sudan" },
  { value: "es", label: "إسبانيا - Spain" },
  { value: "lk", label: "سريلانكا - Sri Lanka" },
  { value: "sd", label: "السودان - Sudan" },
  { value: "sr", label: "سورينام - Suriname" },
  { value: "sj", label: "سفالبارد وجان ماين - Svalbard and Jan Mayen" },
  { value: "se", label: "السويد - Sweden" },
  { value: "ch", label: "سويسرا - Switzerland" },
  { value: "sy", label: "سوريا - Syria" },
  { value: "tw", label: "تايوان - Taiwan" },
  { value: "tj", label: "طاجيكستان - Tajikistan" },
  { value: "tz", label: "تنزانيا - Tanzania" },
  { value: "th", label: "تايلاند - Thailand" },
  { value: "tl", label: "تيمور الشرقية - Timor-Leste" },
  { value: "tg", label: "توغو - Togo" },
  { value: "tk", label: "توكيلو - Tokelau" },
  { value: "to", label: "تونغا - Tonga" },
  { value: "tt", label: "ترينيداد وتوباغو - Trinidad and Tobago" },
  { value: "tn", label: "تونس - Tunisia" },
  { value: "tr", label: "تركيا - Turkey" },
  { value: "tm", label: "تركمانستان - Turkmenistan" },
  { value: "tc", label: "جزر تركس وكايكوس - Turks and Caicos Islands" },
  { value: "tv", label: "توفالو - Tuvalu" },
  { value: "ug", label: "أوغندا - Uganda" },
  { value: "ua", label: "أوكرانيا - Ukraine" },
  { value: "ae", label: "الإمارات - United Arab Emirates" },
  { value: "gb", label: "المملكة المتحدة - United Kingdom" },
  { value: "um", label: "جزر الولايات المتحدة النائية الصغيرة - U.S. Outlying Islands" },
  { value: "us", label: "الولايات المتحدة - United States" },
  { value: "uy", label: "أوروغواي - Uruguay" },
  { value: "uz", label: "أوزبكستان - Uzbekistan" },
  { value: "vu", label: "فانواتو - Vanuatu" },
  { value: "va", label: "الفاتيكان - Vatican City" },
  { value: "ve", label: "فنزويلا - Venezuela" },
  { value: "vn", label: "فيتنام - Vietnam" },
  { value: "vg", label: "جزر العذراء البريطانية - British Virgin Islands" },
  { value: "vi", label: "جزر العذراء الأمريكية - U.S. Virgin Islands" },
  { value: "wf", label: "جزر واليس وفوتونا - Wallis and Futuna" },
  { value: "eh", label: "الصحراء الغربية - Western Sahara" },
  { value: "ye", label: "اليمن - Yemen" },
  { value: "zm", label: "زامبيا - Zambia" },
  { value: "zw", label: "زيمبابوي - Zimbabwe" }
];