// قائمة كل دول العالم مع أكواد الاتصال الدولية وصيغة الأعلام (flag-icons)
export const PHONE_CODES = [
  { code: "+93",  label: "Afghanistan", labelAr: "أفغانستان", flag: "af" },
  { code: "+355", label: "Albania", labelAr: "ألبانيا", flag: "al" },
  { code: "+213", label: "Algeria", labelAr: "الجزائر", flag: "dz" },
  { code: "+1",   label: "United States", labelAr: "الولايات المتحدة", flag: "us" },
  { code: "+376", label: "Andorra", labelAr: "أندورا", flag: "ad" },
  { code: "+244", label: "Angola", labelAr: "أنغولا", flag: "ao" },
  { code: "+1",   label: "Anguilla", labelAr: "أنغيلا", flag: "ai" },
  { code: "+1",   label: "Antigua and Barbuda", labelAr: "أنتيغوا وبربودا", flag: "ag" },
  { code: "+54",  label: "Argentina", labelAr: "الأرجنتين", flag: "ar" },
  { code: "+374", label: "Armenia", labelAr: "أرمينيا", flag: "am" },
  { code: "+297", label: "Aruba", labelAr: "أروبا", flag: "aw" },
  { code: "+61",  label: "Australia", labelAr: "أستراليا", flag: "au" },
  { code: "+43",  label: "Austria", labelAr: "النمسا", flag: "at" },
  { code: "+994", label: "Azerbaijan", labelAr: "أذربيجان", flag: "az" },
  { code: "+973", label: "Bahrain", labelAr: "البحرين", flag: "bh" },
  { code: "+880", label: "Bangladesh", labelAr: "بنغلاديش", flag: "bd" },
  { code: "+1",   label: "Barbados", labelAr: "باربادوس", flag: "bb" },
  { code: "+375", label: "Belarus", labelAr: "بيلاروسيا", flag: "by" },
  { code: "+32",  label: "Belgium", labelAr: "بلجيكا", flag: "be" },
  { code: "+501", label: "Belize", labelAr: "بليز", flag: "bz" },
  { code: "+229", label: "Benin", labelAr: "بنين", flag: "bj" },
  { code: "+1",   label: "Bermuda", labelAr: "برمودا", flag: "bm" },
  { code: "+975", label: "Bhutan", labelAr: "بوتان", flag: "bt" },
  { code: "+591", label: "Bolivia", labelAr: "بوليفيا", flag: "bo" },
  { code: "+387", label: "Bosnia and Herzegovina", labelAr: "البوسنة والهرسك", flag: "ba" },
  { code: "+267", label: "Botswana", labelAr: "بوتسوانا", flag: "bw" },
  { code: "+55",  label: "Brazil", labelAr: "البرازيل", flag: "br" },
  { code: "+246", label: "British Indian Ocean Territory", labelAr: "إقليم المحيط الهندي البريطاني", flag: "io" },
  { code: "+673", label: "Brunei", labelAr: "بروناي", flag: "bn" },
  { code: "+359", label: "Bulgaria", labelAr: "بلغاريا", flag: "bg" },
  { code: "+226", label: "Burkina Faso", labelAr: "بوركينا فاسو", flag: "bf" },
  { code: "+257", label: "Burundi", labelAr: "بوروندي", flag: "bi" },
  { code: "+855", label: "Cambodia", labelAr: "كمبوديا", flag: "kh" },
  { code: "+237", label: "Cameroon", labelAr: "الكاميرون", flag: "cm" },
  { code: "+1",   label: "Canada", labelAr: "كندا", flag: "ca" },
  { code: "+238", label: "Cape Verde", labelAr: "الرأس الأخضر", flag: "cv" },
  { code: "+1",   label: "Cayman Islands", labelAr: "جزر كايمان", flag: "ky" },
  { code: "+236", label: "Central African Republic", labelAr: "جمهورية أفريقيا الوسطى", flag: "cf" },
  { code: "+235", label: "Chad", labelAr: "تشاد", flag: "td" },
  { code: "+56",  label: "Chile", labelAr: "تشيلي", flag: "cl" },
  { code: "+86",  label: "China", labelAr: "الصين", flag: "cn" },
  { code: "+57",  label: "Colombia", labelAr: "كولومبيا", flag: "co" },
  { code: "+269", label: "Comoros", labelAr: "جزر القمر", flag: "km" },
  { code: "+242", label: "Congo", labelAr: "الكونغو", flag: "cg" },
  { code: "+243", label: "Congo (DRC)", labelAr: "الكونغو الديمقراطية", flag: "cd" },
  { code: "+682", label: "Cook Islands", labelAr: "جزر كوك", flag: "ck" },
  { code: "+506", label: "Costa Rica", labelAr: "كوستاريكا", flag: "cr" },
  { code: "+225", label: "Côte d'Ivoire", labelAr: "ساحل العاج", flag: "ci" },
  { code: "+385", label: "Croatia", labelAr: "كرواتيا", flag: "hr" },
  { code: "+53",  label: "Cuba", labelAr: "كوبا", flag: "cu" },
  { code: "+357", label: "Cyprus", labelAr: "قبرص", flag: "cy" },
  { code: "+420", label: "Czechia", labelAr: "التشيك", flag: "cz" },
  { code: "+45",  label: "Denmark", labelAr: "الدنمارك", flag: "dk" },
  { code: "+253", label: "Djibouti", labelAr: "جيبوتي", flag: "dj" },
  { code: "+1",   label: "Dominica", labelAr: "دومينيكا", flag: "dm" },
  { code: "+1",   label: "Dominican Republic", labelAr: "جمهورية الدومينيكان", flag: "do" },
  { code: "+593", label: "Ecuador", labelAr: "الإكوادور", flag: "ec" },
  { code: "+20",  label: "Egypt", labelAr: "مصر", flag: "eg" },
  { code: "+503", label: "El Salvador", labelAr: "السلفادور", flag: "sv" },
  { code: "+240", label: "Equatorial Guinea", labelAr: "غينيا الاستوائية", flag: "gq" },
  { code: "+291", label: "Eritrea", labelAr: "إريتريا", flag: "er" },
  { code: "+372", label: "Estonia", labelAr: "إستونيا", flag: "ee" },
  { code: "+251", label: "Ethiopia", labelAr: "إثيوبيا", flag: "et" },
  { code: "+679", label: "Fiji", labelAr: "فيجي", flag: "fj" },
  { code: "+358", label: "Finland", labelAr: "فنلندا", flag: "fi" },
  { code: "+33",  label: "France", labelAr: "فرنسا", flag: "fr" },
  { code: "+241", label: "Gabon", labelAr: "الغابون", flag: "ga" },
  { code: "+220", label: "Gambia", labelAr: "غامبيا", flag: "gm" },
  { code: "+995", label: "Georgia", labelAr: "جورجيا", flag: "ge" },
  { code: "+49",  label: "Germany", labelAr: "ألمانيا", flag: "de" },
  { code: "+233", label: "Ghana", labelAr: "غانا", flag: "gh" },
  { code: "+350", label: "Gibraltar", labelAr: "جبل طارق", flag: "gi" },
  { code: "+30",  label: "Greece", labelAr: "اليونان", flag: "gr" },
  { code: "+299", label: "Greenland", labelAr: "جرينلاند", flag: "gl" },
  { code: "+1",   label: "Grenada", labelAr: "غرينادا", flag: "gd" },
  { code: "+502", label: "Guatemala", labelAr: "غواتيمالا", flag: "gt" },
  { code: "+224", label: "Guinea", labelAr: "غينيا", flag: "gn" },
  { code: "+245", label: "Guinea-Bissau", labelAr: "غينيا بيساو", flag: "gw" },
  { code: "+592", label: "Guyana", labelAr: "غيانا", flag: "gy" },
  { code: "+509", label: "Haiti", labelAr: "هايتي", flag: "ht" },
  { code: "+504", label: "Honduras", labelAr: "هندوراس", flag: "hn" },
  { code: "+36",  label: "Hungary", labelAr: "المجر", flag: "hu" },
  { code: "+354", label: "Iceland", labelAr: "آيسلندا", flag: "is" },
  { code: "+91",  label: "India", labelAr: "الهند", flag: "in" },
  { code: "+62",  label: "Indonesia", labelAr: "إندونيسيا", flag: "id" },
  { code: "+98",  label: "Iran", labelAr: "إيران", flag: "ir" },
  { code: "+964", label: "Iraq", labelAr: "العراق", flag: "iq" },
  { code: "+353", label: "Ireland", labelAr: "أيرلندا", flag: "ie" },
  { code: "+972", label: "Israel", labelAr: "إسرائيل", flag: "il" },
  { code: "+39",  label: "Italy", labelAr: "إيطاليا", flag: "it" },
  { code: "+1",   label: "Jamaica", labelAr: "جامايكا", flag: "jm" },
  { code: "+81",  label: "Japan", labelAr: "اليابان", flag: "jp" },
  { code: "+962", label: "Jordan", labelAr: "الأردن", flag: "jo" },
  { code: "+7",   label: "Kazakhstan", labelAr: "كازاخستان", flag: "kz" },
  { code: "+254", label: "Kenya", labelAr: "كينيا", flag: "ke" },
  { code: "+686", label: "Kiribati", labelAr: "كيريباتي", flag: "ki" },
  { code: "+965", label: "Kuwait", labelAr: "الكويت", flag: "kw" },
  { code: "+996", label: "Kyrgyzstan", labelAr: "قرغيزستان", flag: "kg" },
  { code: "+856", label: "Laos", labelAr: "لاوس", flag: "la" },
  { code: "+371", label: "Latvia", labelAr: "لاتفيا", flag: "lv" },
  { code: "+961", label: "Lebanon", labelAr: "لبنان", flag: "lb" },
  { code: "+266", label: "Lesotho", labelAr: "ليسوتو", flag: "ls" },
  { code: "+231", label: "Liberia", labelAr: "ليبيريا", flag: "lr" },
  { code: "+218", label: "Libya", labelAr: "ليبيا", flag: "ly" },
  { code: "+423", label: "Liechtenstein", labelAr: "ليختنشتاين", flag: "li" },
  { code: "+370", label: "Lithuania", labelAr: "ليتوانيا", flag: "lt" },
  { code: "+352", label: "Luxembourg", labelAr: "لوكسمبورغ", flag: "lu" },
  { code: "+853", label: "Macau", labelAr: "ماكاو", flag: "mo" },
  { code: "+389", label: "North Macedonia", labelAr: "مقدونيا الشمالية", flag: "mk" },
  { code: "+261", label: "Madagascar", labelAr: "مدغشقر", flag: "mg" },
  { code: "+265", label: "Malawi", labelAr: "مالاوي", flag: "mw" },
  { code: "+60",  label: "Malaysia", labelAr: "ماليزيا", flag: "my" },
  { code: "+960", label: "Maldives", labelAr: "المالديف", flag: "mv" },
  { code: "+223", label: "Mali", labelAr: "مالي", flag: "ml" },
  { code: "+356", label: "Malta", labelAr: "مالطا", flag: "mt" },
  { code: "+692", label: "Marshall Islands", labelAr: "جزر مارشال", flag: "mh" },
  { code: "+222", label: "Mauritania", labelAr: "موريتانيا", flag: "mr" },
  { code: "+230", label: "Mauritius", labelAr: "موريشيوس", flag: "mu" },
  { code: "+52",  label: "Mexico", labelAr: "المكسيك", flag: "mx" },
  { code: "+691", label: "Micronesia", labelAr: "ميكرونيزيا", flag: "fm" },
  { code: "+373", label: "Moldova", labelAr: "مولدوفا", flag: "md" },
  { code: "+377", label: "Monaco", labelAr: "موناكو", flag: "mc" },
  { code: "+976", label: "Mongolia", labelAr: "منغوليا", flag: "mn" },
  { code: "+382", label: "Montenegro", labelAr: "الجبل الأسود", flag: "me" },
  { code: "+212", label: "Morocco", labelAr: "المغرب", flag: "ma" },
  { code: "+258", label: "Mozambique", labelAr: "موزمبيق", flag: "mz" },
  { code: "+95",  label: "Myanmar", labelAr: "ميانمار", flag: "mm" },
  { code: "+264", label: "Namibia", labelAr: "ناميبيا", flag: "na" },
  { code: "+674", label: "Nauru", labelAr: "ناورو", flag: "nr" },
  { code: "+977", label: "Nepal", labelAr: "نيبال", flag: "np" },
  { code: "+31",  label: "Netherlands", labelAr: "هولندا", flag: "nl" },
  { code: "+64",  label: "New Zealand", labelAr: "نيوزيلندا", flag: "nz" },
  { code: "+505", label: "Nicaragua", labelAr: "نيكاراغوا", flag: "ni" },
  { code: "+227", label: "Niger", labelAr: "النيجر", flag: "ne" },
  { code: "+234", label: "Nigeria", labelAr: "نيجيريا", flag: "ng" },
  { code: "+47",  label: "Norway", labelAr: "النرويج", flag: "no" },
  { code: "+968", label: "Oman", labelAr: "عمان", flag: "om" },
  { code: "+92",  label: "Pakistan", labelAr: "باكستان", flag: "pk" },
  { code: "+680", label: "Palau", labelAr: "بالاو", flag: "pw" },
  { code: "+970", label: "Palestine", labelAr: "فلسطين", flag: "ps" },
  { code: "+507", label: "Panama", labelAr: "بنما", flag: "pa" },
  { code: "+675", label: "Papua New Guinea", labelAr: "بابوا غينيا الجديدة", flag: "pg" },
  { code: "+595", label: "Paraguay", labelAr: "باراغواي", flag: "py" },
  { code: "+51",  label: "Peru", labelAr: "بيرو", flag: "pe" },
  { code: "+63",  label: "Philippines", labelAr: "الفلبين", flag: "ph" },
  { code: "+48",  label: "Poland", labelAr: "بولندا", flag: "pl" },
  { code: "+351", label: "Portugal", labelAr: "البرتغال", flag: "pt" },
  { code: "+1",   label: "Puerto Rico", labelAr: "بورتو ريكو", flag: "pr" },
  { code: "+974", label: "Qatar", labelAr: "قطر", flag: "qa" },
  { code: "+40",  label: "Romania", labelAr: "رومانيا", flag: "ro" },
  { code: "+7",   label: "Russia", labelAr: "روسيا", flag: "ru" },
  { code: "+250", label: "Rwanda", labelAr: "رواندا", flag: "rw" },
  { code: "+590", label: "Saint Barthélemy", labelAr: "سانت بارتيليمي", flag: "bl" },
  { code: "+290", label: "Saint Helena", labelAr: "سانت هيلينا", flag: "sh" },
  { code: "+1",   label: "Saint Kitts and Nevis", labelAr: "سانت كيتس ونيفيس", flag: "kn" },
  { code: "+1",   label: "Saint Lucia", labelAr: "سانت لوسيا", flag: "lc" },
  { code: "+590", label: "Saint Martin", labelAr: "سانت مارتن", flag: "mf" },
  { code: "+508", label: "Saint Pierre and Miquelon", labelAr: "سان بيير وميكلون", flag: "pm" },
  { code: "+1",   label: "Saint Vincent and the Grenadines", labelAr: "سانت فنسنت والغرينادين", flag: "vc" },
  { code: "+685", label: "Samoa", labelAr: "ساموا", flag: "ws" },
  { code: "+378", label: "San Marino", labelAr: "سان مارينو", flag: "sm" },
  { code: "+239", label: "Sao Tome and Principe", labelAr: "ساو تومي وبرينسيب", flag: "st" },
  { code: "+966", label: "Saudi Arabia", labelAr: "السعودية", flag: "sa" },
  { code: "+221", label: "Senegal", labelAr: "السنغال", flag: "sn" },
  { code: "+381", label: "Serbia", labelAr: "صربيا", flag: "rs" },
  { code: "+248", label: "Seychelles", labelAr: "سيشل", flag: "sc" },
  { code: "+232", label: "Sierra Leone", labelAr: "سيراليون", flag: "sl" },
  { code: "+65",  label: "Singapore", labelAr: "سنغافورة", flag: "sg" },
  { code: "+421", label: "Slovakia", labelAr: "سلوفاكيا", flag: "sk" },
  { code: "+386", label: "Slovenia", labelAr: "سلوفينيا", flag: "si" },
  { code: "+677", label: "Solomon Islands", labelAr: "جزر سليمان", flag: "sb" },
  { code: "+252", label: "Somalia", labelAr: "الصومال", flag: "so" },
  { code: "+27",  label: "South Africa", labelAr: "جنوب أفريقيا", flag: "za" },
  { code: "+82",  label: "South Korea", labelAr: "كوريا الجنوبية", flag: "kr" },
  { code: "+211", label: "South Sudan", labelAr: "جنوب السودان", flag: "ss" },
  { code: "+34",  label: "Spain", labelAr: "إسبانيا", flag: "es" },
  { code: "+94",  label: "Sri Lanka", labelAr: "سريلانكا", flag: "lk" },
  { code: "+249", label: "Sudan", labelAr: "السودان", flag: "sd" },
  { code: "+597", label: "Suriname", labelAr: "سورينام", flag: "sr" },
  { code: "+46",  label: "Sweden", labelAr: "السويد", flag: "se" },
  { code: "+41",  label: "Switzerland", labelAr: "سويسرا", flag: "ch" },
  { code: "+963", label: "Syria", labelAr: "سوريا", flag: "sy" },
  { code: "+886", label: "Taiwan", labelAr: "تايوان", flag: "tw" },
  { code: "+992", label: "Tajikistan", labelAr: "طاجيكستان", flag: "tj" },
  { code: "+255", label: "Tanzania", labelAr: "تنزانيا", flag: "tz" },
  { code: "+66",  label: "Thailand", labelAr: "تايلاند", flag: "th" },
  { code: "+228", label: "Togo", labelAr: "توغو", flag: "tg" },
  { code: "+676", label: "Tonga", labelAr: "تونغا", flag: "to" },
  { code: "+1",   label: "Trinidad and Tobago", labelAr: "ترينيداد وتوباغو", flag: "tt" },
  { code: "+216", label: "Tunisia", labelAr: "تونس", flag: "tn" },
  { code: "+90",  label: "Turkey", labelAr: "تركيا", flag: "tr" },
  { code: "+993", label: "Turkmenistan", labelAr: "تركمانستان", flag: "tm" },
  { code: "+688", label: "Tuvalu", labelAr: "توفالو", flag: "tv" },
  { code: "+256", label: "Uganda", labelAr: "أوغندا", flag: "ug" },
  { code: "+380", label: "Ukraine", labelAr: "أوكرانيا", flag: "ua" },
  { code: "+971", label: "United Arab Emirates", labelAr: "الإمارات", flag: "ae" },
  { code: "+44",  label: "United Kingdom", labelAr: "المملكة المتحدة", flag: "gb" },
  { code: "+598", label: "Uruguay", labelAr: "أوروغواي", flag: "uy" },
  { code: "+998", label: "Uzbekistan", labelAr: "أوزبكستان", flag: "uz" },
  { code: "+678", label: "Vanuatu", labelAr: "فانواتو", flag: "vu" },
  { code: "+58",  label: "Venezuela", labelAr: "فنزويلا", flag: "ve" },
  { code: "+84",  label: "Vietnam", labelAr: "فيتنام", flag: "vn" },
  { code: "+967", label: "Yemen", labelAr: "اليمن", flag: "ye" },
  { code: "+260", label: "Zambia", labelAr: "زامبيا", flag: "zm" },
  { code: "+263", label: "Zimbabwe", labelAr: "زيمبابوي", flag: "zw" },
];